version: "3"
services:
  db:
    container_name: hairday-db
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hairday
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
